### ISSUE TITLE
login nicht möglich mercedes me

### ISSUE THREAD

**Issue by lwillibald** [TA2k/ioBroker.mercedesme#116]
hallo ab der neuern version 0.0.55 ist das anmelden nicht mehr möglich
bekomme einen email code aber es meldet sich nicht an mit meinen account 
mit der version 0.0.53 hat es funktioniert

**Comment by TA2k** [comment]
Bei mir geht es. manchmal werden mehrere codes gesendet immer den letzen nehmen

**Comment by lwillibald** [comment]
hab ich gemacht 
hab deinstalliert und wieder installiert jetzt kommt kein Codes zurück
hab auch das installiert npm i iobroker.mercedesme

**Comment by TA2k** [comment]
Geht denn der login via app denn?

**Comment by lwillibald** [comment]
ja über App kein Problem  wie gesagt mit der version 0.0.54 wars ok

**Comment by TA2k** [comment]
vielleicht den adapter nochmal löschen
