### ISSUE TITLE
Sync funktioniert nicht mehr

### ISSUE THREAD

**Issue by irudi** [TA2k/ioBroker.mercedesme#129]
Ich bekomme neuerdings einen Fehler, wenn der Adapter sich synchronisiert

{"code":404,"message":"path /v1/vehicle/self/masterdata was not found"}

Ich habe mal danach gesucht und dies gefunden, was auf eine kürzliche API Änderung hindeutet:
https://community.home-assistant.io/t/mercedes-me-component/41911/1119

**Comment by TA2k** [comment]
Bitte  auf 0.0.56 updaten

**Comment by irudi** [comment]
Danke, perfekt!
Hatte nicht gesehen, dass es schon ein Update gibt.
