### ISSUE TITLE
Adapter ruft Mercedes me vermutlich falsch auf

### ISSUE THREAD

**Issue by fhilgenb** [TA2k/ioBroker.mercedesme#14]
Wir haben gesehen, dass Sie einen Mercedes me Adapter für den ioBroker (https://www.iobroker.net/#de/adapters/adapterref/iobroker.mercedesme/README.md) zur Verfügung stellen. Wir entwicklen und betreiben Mercedes me. Bei der Analyse unsere Logs ist uns aufgefallen, dass wahrscheinlich Aufrufe über diesen Adapter bei uns ankommen, die auf Fehler laufen. Ich würde gerne mit Ihnen besprechen, was nötig ist, dass der Adapter nicht auf diese Fehler läuft, die gewiss nicht vom Adapter beabsichtigt sind und aus unserer Sicht auch zu Fehlern bei den Kunden führen, die den Adapter einsetzen.

Danke und Gruß.

**Comment by TA2k** [comment]
Danke für die Anfrage ich habe Ihre Mail beantwortet
