### ISSUE TITLE
Absturz bei Adapter-Start

### ISSUE THREAD

**Issue by dpomt** [TA2k/ioBroker.mercedesme#166]
Hallo,

habe heute meine gesamte ältere ioBroker-Installation auf den aktuellen Stand gebracht. mercedesme-Adapter auf 0.0.56
Danach lief er erstmal. Da es state.tanklevelpercent.displayValue nicht mehr gab, hab ich Objektbaum komplett gelöscht und Adapter danach neu gestartet.
Jetzt stürzt der Adapter beim Start ab:

![image](https://user-images.githubusercontent.com/1379660/170872100-c432a377-c125-4dce-a8ae-cb7829e683b0.png)

Wie bekomme ich den Adapter wieder zum Laufen?

**Comment by TA2k** [comment]
Sollte eigentlich nicht passieren.
Entweder den Ordner auth löschen
oder Adapter komplett löschen und neuinstallieren

**Comment by dpomt** [comment]
> Sollte eigentlich nicht passieren. Entweder den Ordner auth löschen oder Adapter komplett löschen und neuinstallieren

Danke. Löschen und Neuinstallation Adapter hat funktioniert.
