### ISSUE TITLE
mercedesme.0	2020-08-25 08:38:48.075	info	(6835) starting. Version 0.0.21 in /opt/iobroker/node_modules/iobroker.mercedesme, node: v10.22.0, js-controller: 3.1.6

### ISSUE THREAD

**Issue by hpiecuch** [TA2k/ioBroker.mercedesme#17]
Is there someone who can help regarding that json issue!

mercedesme.0 | 2020-08-25 11:49:11.363 | error | (14142) Error getting Vehicles
-- | -- | -- | --
mercedesme.0 | 2020-08-25 11:49:11.361 | warn | (14142) Vehicles not found please start the mercedes me app: SyntaxError: Unexpected token u in JSON at position 0

![image](https://user-images.githubusercontent.com/70193797/91183383-b2d18500-e6eb-11ea-97d7-abf69d64ffaf.png)

![image](https://user-images.githubusercontent.com/70193797/91183482-d268ad80-e6eb-11ea-84a9-2e037bf5ddd4.png)

**Comment by Tripmaster7** [comment]
Same here.
