### ISSUE TITLE
Fahrzeuge werden nicht richtig erstellt 

### ISSUE THREAD

**Issue by kilian-f-za** [TA2k/ioBroker.mercedesme#182]
Mein neues Fahrzeug wird in den Objekten nicht richtig erstellt. Es wird nur der Ordner state erstellt. Ich habe bereits mehrmals versucht den gesamten Mercedesme Order zu löschen. Ich habe auch probiert mein Fahrzeug aus der Mercedes App zu löschen. Beides hat nicht geholfen. Es steht überall null drin.

Admin Adapter: 6.2.17
Nodejs: v12.22.12
Mercedesme: v0.0.56

Hat jemand eine Idee?

**Comment by TA2k** [comment]
Ich benötige ein debug log via mail
tombox2020@gmail.com

**Comment by kilian-f-za** [comment]
Aus dem Web admin oder woher?

**Comment by TA2k** [comment]
Korrekt die Instanz auf log level debug setzen und dann im log Fenster den Inhalt kopieren

**Comment by kilian-f-za** [comment]
OK, ich schaue Mal. 
Der Adapter startet aber und wird auch grün nur halt nicht richtig angelegt bzw. fehlen auch Datenpunkte.

**Comment by gaga191281** [comment]
+1
mein für mein neues Fahrzeug werden zwei Ordner angelegt. Einer mit der richtigen VIN indem nur state enthalten ist, und einer mit einer falschen VIN welche aber die gleiche Endung hat, indem die anderen Datenpunkte (remote, etc.) sind. Jedoch haben diese keine Auswirkung (Vorklimatisierung starten, Tür öffnen geht alles nicht).

**Comment by TA2k** [comment]
Ich bräuchte ein account um das nachzustellen
tombox2020@gmail.com

**Comment by gaga191281** [comment]
Interessant ist, das fin und vin unterschiedlich sind. Sollten die nicht identisch sein? Ist doch dasselbe. (Einmal deutsch, einmal englisch)
![image](https://user-images.githubusercontent.com/60061155/192535421-29994b8c-c685-4995-8b34-0fdbd45cac41.png)

**Comment by kilian-f-za** [comment]
> Interessant ist, das fin und vin unterschiedlich sind. Sollten die nicht identisch sein? Ist doch dasselbe. (Einmal deutsch, einmal englisch)
> ![image](https://user-images.githubusercontent.com/60061155/192535421-29994b8c-c685-4995-8b34-0fdbd45cac41.png)
> 

Da ist korrekt, Mercedes hat seit ein paar Monaten von der FIN auf die VIN umgestellt. Die "alte" FIN läuft bei den neuen Fahrzeugen nur noch im Background und soll irgendwann nicht mehr genutzt werden. In der Mercedes Me App wird auch nur noch die VIN genutzt.
Der Händler sieht in seiner Ansicht auch nur die neue VIN.

**Comment by gaga191281** [comment]
> > Interessant ist, das fin und vin unterschiedlich sind. Sollten die nicht identisch sein? Ist doch dasselbe. (Einmal deutsch, einmal englisch)
> > ![image](https://user-images.githubusercontent.com/60061155/192535421-29994b8c-c685-4995-8b34-0fdbd45cac41.png)
> 
> Da ist korrekt, Mercedes hat seit ein paar Monaten von der FIN auf die VIN umgestellt. Die "alte" FIN läuft bei den neuen Fahrzeugen nur noch im Background und soll irgendwann nicht mehr genutzt werden. In der Mercedes Me App wird auch nur noch die VIN genutzt. Der Händler sieht in seiner Ansicht auch nur die neue VIN.

Und hier scheint das Problem zu liegen. Denn unter FIN werden 'commands, 'history, 'masterdata', 'remote', 'user' und der Datenpunkt 'geofencing' abgelegt.
Der Adapter beschwert sich in den Logs auch darüber dass Datenpunkte aus 'remote' für die vin fehlen.

PS: der 'RIS_FORBIDDEN_VIN' ist nun auch wieder aufgetaucht:
![image](https://user-images.githubusercontent.com/60061155/192539347-2e3715ec-6955-4046-aab9-eadee129f97c.png)

**Comment by gaga191281** [comment]
Die VIN ist auch die, die bei mir im Fahzeugschein steht.

**Comment by TA2k** [comment]
Installier mal die GitHub version und lösche mercedeme.0. Objekt und starte den Adapter neu

**Comment by gaga191281** [comment]
> Installier mal die GitHub version und lösche mercedeme.0. Objekt und starte den Adapter neu

Sehr nice.. das hat geholfen.
Super, danke. Jetzt scheint alles richtig erstellt worden zu sein. Starten der Vorklimatisierung hat auch geklappt.

**Comment by kilian-f-za** [comment]
Ich habe jetzt auch die GitHub Version installiert. Die Fahrzeuge werden richtig erstellt, top super. Ich kann allerdings die remote Befehle und commands nicht ausführen. Folgende Meldung kommt: 	[{"code":"CMD_REJECTED_BY_QUEUE","message":"Command was rejected due to blocked command queue.","attributesMap":[],"subErrorsList":[]}]

Habe alle mercedesme.0 Objekte gelöscht.

**Comment by TA2k** [comment]
Klingt eigenartig. Über die app geht es? Mal das Auto ein und ausschalten

**Comment by kilian-f-za** [comment]
> Klingt eigenartig. Über die app geht es? Mal das Auto ein und ausschalten

Die App lädt auch ewig. Ich werde Mal das Auto bewegen. Danke.

**Comment by kilian-f-za** [comment]
> Klingt eigenartig. Über die app geht es? Mal das Auto ein und ausschalten

Jetzt funktioniert alles perfekt auch die remote Befehle kommen an. Top danke
