### ISSUE TITLE
	AssertionError: Failure: Invalid wire type: 7 (at position 0)

### ISSUE THREAD

**Issue by Stefan-83** [TA2k/ioBroker.mercedesme#188]
**Describe the bug**  
since today, I get this error in the logfiles:
AssertionError: Failure: Invalid wire type: 7 (at position 0)

No change in the configuration

**Comment by TA2k** [comment]
is the mercedes me app working?

**Comment by TA2k** [comment]
do you use version 0.1.0 ?

**Comment by HJS72** [comment]
Same here with Version 0.0.59. How can I get 0.1.0? Current Version ist 0.0.59

**Comment by TA2k** [comment]
Wait 24h or install via npm

**Comment by iobFan** [comment]
I got the same errors with version 0.0.59

**Comment by GieGit** [comment]
version 0.1.0 has just been released in stable, after update the error is gone

**Comment by Stefan-83** [comment]
Confirmed 👍🏼 
Works again 
Thanks
