### ISSUE TITLE
Websocket Parse Error

### ISSUE THREAD

**Issue by nmehnert73** [TA2k/ioBroker.mercedesme#189]
Since a few days the adapter doesn't work anymore. Ich receive the messages attached. What can I do?
![image](https://user-images.githubusercontent.com/112388389/204485885-aad850ee-0537-47f1-9388-4b8d599484ff.png)

**Comment by TA2k** [comment]
Please update the adapter

**Comment by nmehnert73** [comment]
It seems that the most current version is installed.
![image](https://user-images.githubusercontent.com/112388389/204486621-3b5ea7cd-f6cc-4fa2-b69c-0f1c77f61ec3.png)

**Comment by TA2k** [comment]
Please try to refresh the update list or install directly via npm

**Comment by nmehnert73** [comment]
Thank you! Now it works fine again! 👍
