### ISSUE TITLE
Login is not working 0.34

### ISSUE THREAD

**Issue by peterbaumert** [TA2k/ioBroker.mercedesme#19]
**Describe the bug**  
Asks me everytime for login token and if i provide it, it says its wrong.

**Screenshots & Logfiles**  
`

mercedesme.0 | 2020-11-16 17:08:41.551 | error | (32233) adapter disabled
-- | -- | -- | --
mercedesme.0 | 2020-11-16 17:08:41.494 | debug | (32233) Plugin sentry Initialize Plugin (enabled=true)
mercedesme.0 | 2020-11-16 17:08:40.714 | debug | (32233) statesDB connected
mercedesme.0 | 2020-11-16 17:08:40.712 | debug | (32233) States connected to redis: 127.0.0.1:9000
mercedesme.0 | 2020-11-16 17:08:40.705 | debug | (32233) States create System PubSub Client
mercedesme.0 | 2020-11-16 17:08:40.702 | debug | (32233) States create User PubSub Client
mercedesme.0 | 2020-11-16 17:08:40.697 | debug | (32233) Redis States: Use Redis connection: 127.0.0.1:9000
mercedesme.0 | 2020-11-16 17:08:40.696 | debug | (32233) objectDB connected
mercedesme.0 | 2020-11-16 17:08:40.693 | debug | (32233) Objects connected to redis: 127.0.0.1:9001
mercedesme.0 | 2020-11-16 17:08:40.676 | debug | (32233) Objects client initialize lua scripts
mercedesme.0 | 2020-11-16 17:08:40.675 | debug | (32233) Objects create User PubSub Client
mercedesme.0 | 2020-11-16 17:08:40.673 | debug | (32233) Objects create System PubSub Client
mercedesme.0 | 2020-11-16 17:08:40.670 | debug | (32233) Objects client ready ... initialize now
mercedesme.0 | 2020-11-16 17:08:40.638 | debug | (32233) Redis Objects: Use Redis connection: 127.0.0.1:9001
mercedesme.0 | 2020-11-16 17:08:36.650 | info | (31977) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
mercedesme.0 | 2020-11-16 17:08:36.649 | debug | (31977) Plugin sentry destroyed
mercedesme.0 | 2020-11-16 17:08:36.649 | info | (31977) terminating
mercedesme.0 | 2020-11-16 17:08:36.648 | info | (31977) Got terminate signal TERMINATE_YOURSELF
mercedesme.0 | 2020-11-16 17:08:36.647 | silly | (31977) States system redis pmessage system.adapter.mercedesme.0.sigKill/system.adapter.mercedesme.0.sigKill:{"val":-1,"ack":false,"ts":1605542916645,"q":0,"from":"system.host.iobroker","lc":16055429
mercedesme.0 | 2020-11-16 17:08:36.631 | error | (31977) Error: Request failed with status code 401
mercedesme.0 | 2020-11-16 17:08:36.630 | error | (31977) Wrong Sicherheitscode please enter the new code you received via mail
mercedesme.0 | 2020-11-16 17:08:36.518 | silly | (31977) States system redis pmessage system.adapter.mercedesme.0.logLevel/system.adapter.mercedesme.0.logLevel:{"val":"silly","ack":true,"ts":1605542916472,"q":0,"from":"system.adapter.mercedesme.0",
mercedesme.0 | 2020-11-16 17:08:36.470 | debug | (31977) Login
mercedesme.0 | 2020-11-16 17:08:36.452 | info | (31977) starting. Version 0.0.32 in /opt/iobroker/node_modules/iobroker.mercedesme, node: v12.19.0, js-controller: 3.1.6
mercedesme.0 | 2020-11-16 17:08:36.362 | debug | (31977) Plugin sentry Initialize Plugin (enabled=true)
mercedesme.0 | 2020-11-16 17:08:35.268 | debug | (31977) statesDB connected
mercedesme.0 | 2020-11-16 17:08:35.268 | debug | (31977) States connected to redis: 127.0.0.1:9000
mercedesme.0 | 2020-11-16 17:08:35.259 | debug | (31977) States create System PubSub Client
mercedesme.0 | 2020-11-16 17:08:35.258 | debug | (31977) States create User PubSub Client
mercedesme.0 | 2020-11-16 17:08:35.251 | debug | (31977) Redis States: Use Redis connection: 127.0.0.1:9000
mercedesme.0 | 2020-11-16 17:08:35.250 | debug | (31977) objectDB connected
mercedesme.0 | 2020-11-16 17:08:35.247 | debug | (31977) Objects connected to redis: 127.0.0.1:9001
mercedesme.0 | 2020-11-16 17:08:35.229 | debug | (31977) Objects client initialize lua scripts
mercedesme.0 | 2020-11-16 17:08:35.228 | debug | (31977) Objects create User PubSub Client
mercedesme.0 | 2020-11-16 17:08:35.228 | debug | (31977) Objects create System PubSub Client
mercedesme.0 | 2020-11-16 17:08:35.226 | debug | (31977) Objects client ready ... initialize now
mercedesme.0 | 2020-11-16 17:08:35.188 | debug | (31977) Redis Objects: Use Redis connection: 127.0.0.1:9001
mercedesme.0 | 2020-11-16 17:08:30.733 | info | (31462) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
mercedesme.0 | 2020-11-16 17:08:30.733 | debug | (31462) Plugin sentry destroyed
mercedesme.0 | 2020-11-16 17:08:30.733 | info | (31462) terminating
mercedesme.0 | 2020-11-16 17:08:30.732 | info | (31462) Got terminate signal TERMINATE_YOURSELF
mercedesme.0 | 2020-11-16 17:08:30.732 | silly | (31462) States system redis pmessage system.adapter.mercedesme.0.sigKill/system.adapter.mercedesme.0.sigKill:{"val":-1,"ack":false,"ts":1605542910729,"q":0,"from":"system.host.iobroker","lc":16055429
mercedesme.0 | 2020-11-16 17:08:20.399 | debug | (31462) system.adapter.admin.0: logging true
mercedesme.0 | 2020-11-16 17:08:20.399 | silly | (31462) States system redis pmessage *.logging/system.adapter.admin.0.logging:{"val":true,"ack":true,"ts":1605542900387,"q":0,"from":"system.adapter.admin.0","lc":1605542900387}
mercedesme.0 | 2020-11-16 17:08:18.280 | silly | (31462) States user redis pmessage mercedesme.0.*/mercedesme.0.info.connection:{"val":false,"ack":true,"ts":1605542898268,"q":0,"from":"system.adapter.mercedesme.0","user":"system.user.admin","lc":16
mercedesme.0 | 2020-11-16 17:08:18.180 | error | (31462) Login was not successful.
mercedesme.0 | 2020-11-16 17:08:18.178 | info | (31462) Please enter the code you received via mail in the instance settings
mercedesme.0 | 2020-11-16 17:08:18.178 | debug | (31462) {"isEmail":true,"username":"**MY EMAIL**"}
mercedesme.0 | 2020-11-16 17:08:18.178 | debug | (31462) 200
mercedesme.0 | 2020-11-16 17:08:17.664 | silly | (31462) States system redis pmessage system.adapter.mercedesme.0.logLevel/system.adapter.mercedesme.0.logLevel:{"val":"silly","ack":true,"ts":1605542897622,"q":0,"from":"system.adapter.mercedesme.0",
mercedesme.0 | 2020-11-16 17:08:17.619 | debug | (31462) Login
mercedesme.0 | 2020-11-16 17:08:17.602 | info | (31462) starting. Version 0.0.32 in /opt/iobroker/node_modules/iobroker.mercedesme, node: v12.19.0, js-controller: 3.1.6
mercedesme.0 | 2020-11-16 17:08:17.486 | debug | (31462) Plugin sentry Initialize Plugin (enabled=true)
mercedesme.0 | 2020-11-16 17:08:16.851 | debug | (31462) statesDB connected
mercedesme.0 | 2020-11-16 17:08:16.851 | debug | (31462) States connected to redis: 127.0.0.1:9000
mercedesme.0 | 2020-11-16 17:08:16.841 | debug | (31462) States create System PubSub Client
mercedesme.0 | 2020-11-16 17:08:16.838 | debug | (31462) States create User PubSub Client
mercedesme.0 | 2020-11-16 17:08:16.831 | debug | (31462) Redis States: Use Redis connection: 127.0.0.1:9000
mercedesme.0 | 2020-11-16 17:08:16.830 | debug | (31462) objectDB connected
mercedesme.0 | 2020-11-16 17:08:16.827 | debug | (31462) Objects connected to redis: 127.0.0.1:9001
mercedesme.0 | 2020-11-16 17:08:16.815 | debug | (31462) Objects client initialize lua scripts
mercedesme.0 | 2020-11-16 17:08:16.815 | debug | (31462) Objects create User PubSub Client
mercedesme.0 | 2020-11-16 17:08:16.814 | debug | (31462) Objects create System PubSub Client
mercedesme.0 | 2020-11-16 17:08:16.804 | debug | (31462) Objects client ready ... initialize now
mercedesme.0 | 2020-11-16 17:08:16.711 | debug | (31462) Redis Objects: Use Redis connection: 127.0.0.1:9001

`

**Versions:**  
 - Adapter version: 0.34
 - JS-Controller version: 3.1.6
 - Node version: v12.19.0
 - Operating system: Debian 10

**Comment by PatrickDa87** [comment]
Hallo, du hast vermutlich den falschen Sicherheitscode eingegeben --> 

(31977) Wrong Sicherheitscode please enter the new code you received via mail
--

Bei mir klappt der Login mit Version 0.34

**Comment by peterbaumert** [comment]
Hey, nein nur eine. Und ist definitiv immer der richtige. Habe das 10 mal getestet und es kam immer nur eine mal und dass ich mich so oft vertippe ist zwar nicht ausgeschlossen aber ich habe es überprüft :D

**Comment by TA2k** [comment]
Bitte mal den Adapter für ein halben Tag ausschalten und dann einmal einschalten und auf die Mail warten.

**Comment by peterbaumert** [comment]
@TA2k hab mal einen PR gemacht in dem das Problem behoben wird. Lag daran dass ich in meine mail ein "+" habe.
