### ISSUE TITLE
charge status is no longer displayed

### ISSUE THREAD

**Issue by GieGit** [TA2k/ioBroker.mercedesme#192]
**Describe the bug**  
I use the adapter for a very long time. I show in my VIS if the car is charging.
For this I use the datapoints "mercedesme.0.W1N16xxxxxxxxxx.state.chargingactive.boolValue" that
which until now always jumped from false to true. Since 2-3 days it does not do that anymore. The values in
"mercedesme.0.W1N16xxxxxxxx.state.endofchargetime.displayValue" and mercedesme.0.W1N16xxxxxxxx.state.chargingPower.doubleValue"
display the current values analog to the app.
 
**Versions:**  
 - Adapter version: v0.1.1
 - JS-Controller version: 4.0.24
 - Node version: v16.19.1
 - Operating system: DEBIAN

**Comment by TA2k** [comment]
This is a change in the mercedes api. I have no influence on this
