### ISSUE TITLE
Login Problem

### ISSUE THREAD

**Issue by GerdBautsch** [TA2k/ioBroker.mercedesme#196]
**Describe the bug**  
I have still the login problem. 

**To Reproduce**  
1. After start of the instance I've got a Pin via e-mail
2. Entering the Pin and store it in the window of the instance
3. Login was not successful and periodical a new Pin is requested
4. The example of the Logfile shows only on request 

**Screenshots & Logfiles**  
host.iobroker | 2023-07-30 07:17:26.307 | info | instance system.adapter.mercedesme.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
-- | -- | -- | --
host.iobroker | 2023-07-30 07:17:25.793 | info | stopInstance system.adapter.mercedesme.0 send kill signal
mercedesme.0 | 2023-07-30 07:17:25.732 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
mercedesme.0 | 2023-07-30 07:17:25.731 | info | terminating
mercedesme.0 | 2023-07-30 07:17:25.728 | info | Got terminate signal TERMINATE_YOURSELF
host.iobroker | 2023-07-30 07:17:25.722 | info | stopInstance system.adapter.mercedesme.0 (force=false, process=true)
host.iobroker | 2023-07-30 07:17:25.721 | info | "system.adapter.mercedesme.0" disabled
mercedesme.0 | 2023-07-30 07:17:12.164 | error | Login was not successful.
mercedesme.0 | 2023-07-30 07:17:12.163 | info | Please enter the code you received via mail in the instance settings
mercedesme.0 | 2023-07-30 07:17:11.377 | info | starting.  Version 0.1.3 (non-npm: TA2k/ioBroker.mercedesme) in  /opt/iobroker/node_modules/iobroker.mercedesme, node: v16.19.0,  js-controller: 4.0.24
host.iobroker | 2023-07-30 07:17:08.816 | info | instance system.adapter.mercedesme.0 started with pid 10537
host.iobroker | 2023-07-30 07:17:08.703 | info | "system.adapter.mercedesme.0" enabled

Regards Gerd

**Comment by TA2k** [comment]
please send a debug log to me tombox2020@gmail.com
