### ISSUE TITLE
Objekte

### ISSUE THREAD

**Issue by pockeras** [TA2k/ioBroker.mercedesme#2]
Hallo habe den Adapter erfolgreich installiert und er ist auch grün aber unter Objekte sehe ich keinen Ordner oder Daten 

Mit freundlichen Grüßen

**Comment by TA2k** [comment]
Vielleicht die fin manuell in die Optionen Eintragen

**Comment by pockeras** [comment]
Was ist fin ?

**Comment by HJS72** [comment]
FIN - Fahrzeug Ident Nummer oder auch VIN - Vehicle Ident Number ist umgangssprachlich die Fahrgestellnummer

**Comment by pockeras** [comment]
Ah okay danke das habe ich nicht gewusst 🤪🙈

**Comment by pockeras** [comment]
Geht trotzdem nicht kommt immer error

Error getting Vehicle Details via VHP
mercedesme.0	2019-05-19 21:17:02.634	error	Error getting Vehicle Infos via VHP
mercedesme.0	2019-05-19 21:17:02.630	error	Error getting Vehicle Location via VHP
mercedesme.0	2019-05-19 21:17:02.481	warn	No vehicles found

**Comment by TA2k** [comment]
Werden denn Objekte unter der FIN erzeugt?
Ich benötige Zugang zu so einem Fahrzeug entweder als Mitnutzer eintragen oder per Teamviewer

**Comment by pockeras** [comment]
Ja Objekte wurden erzeugt

**Comment by TA2k** [comment]
Wie heißen die Ordner der Objekte?

**Comment by pockeras** [comment]
Sind 2 einmal fin und der andere heißt so wie mein Fahrgestellnummer die ich in Adapter eingetragen habe

**Comment by hliebscher** [comment]
Hallo bei mir wird nur ein Objekt mit der FIN angelegt
hatte auf debug geschaut. der Login hat geklappt aber dann schein eine Seite keine Daten zu liefern
Error 404 
aber die FIN hat er erkannte und auch meine Userdaten. Leider nur im debug log

mit freundlichen Grüßen
Heiko

**Comment by pockeras** [comment]
Also bei funktioniert es einfach nicht! Ob mit der FIN oder ohne....

**Comment by TA2k** [comment]
Dann bräuchte ich Zugang auf dein Account als Mitbürger oder pee teamviewer melde dich einfach per pn im Forum
