### ISSUE TITLE
Falscher Type bei den Datenpunkten

### ISSUE THREAD

**Issue by Tagiwara** [TA2k/ioBroker.mercedesme#201]
Mir ist aufgefallen, das einige Datenpunkte den falschen Typen haben. Im Falle des Screenshots müsste es vom type number statt string sein.

Ist bei mehreren Datenpunkten so.
![Bildschirmfoto 2023-10-29 um 17 14 00](https://github.com/TA2k/ioBroker.mercedesme/assets/41060053/5759085b-f1bb-47c1-8de9-1e2295a0d0a6)

**Comment by mcm1957** [comment]
Auch role indicator ist definitiv falsch.
Role indicator erfordert als typ boolean.
See https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md

**Comment by TA2k** [comment]
kommt drauf was die api liefert. mal das Objekt löschen und schauen was nach adapter Neustart erstellt wird

**Comment by mcm1957** [comment]
> kommt drauf was die api liefert. mal das Objekt löschen und schauen was nach adapter Neustart erstellt wird

Die Role kann aber definitiv nicht vom API geliefert werden sondern muss der Adapter richtig setzen.

**Comment by TA2k** [comment]
displayValue liefert die API immer als String nur der intValue kommt als number
