### ISSUE TITLE
Incorrect role states

### ISSUE THREAD

**Issue by mcm1957** [TA2k/ioBroker.mercedesme#202]
Several states have incorrect roles, i.e.:

![image](https://github.com/TA2k/ioBroker.mercedesme/assets/28575778/fc279b4c-0579-4bd0-bec3-79cb48196e16)

Role indicator requires type boolean.
Please see https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/stateroles.md for valid roles.

If really optimal role can be assigned use general roles (state, value, level)

**Comment by TA2k** [comment]
fixed in GitHub version

**Comment by mcm1957** [comment]
Thanks
