### ISSUE TITLE
adapter not longer working (websocket parse error) 

### ISSUE THREAD

**Issue by th10mu** [TA2k/ioBroker.mercedesme#205]
iobroker.mercedesme not longer updating status - since this morning?
issue is both in 0.1.1 and 0.1.3, websocket 2.5.8
adapter status changes between green and amber every few seconds
restart of adapter and iobroker server with no effect

mercedesme.0 | 2023-12-14 10:27:08.517 | error | AxiosError: Request failed with status code 418
...
mercedesme.0 | 2023-12-14 09:59:28.655 | error | Error: Assertion failed
mercedesme.0 | 2023-12-14 09:59:28.654 | error | Websocket parse error
mercedesme.0 | 2023-12-14 09:59:23.438 | error | Error: Failure: Invalid wire type: %s (at position %s)
mercedesme.0 | 2023-12-14 09:59:23.438 | error | Websocket parse error
mercedesme.0 | 2023-12-14 09:59:18.243 | error | Error: Assertion failed
mercedesme.0 | 2023-12-14 09:59:18.242 | error | Websocket parse error
mercedesme.0 | 2023-12-14 09:59:13.027 | error | Error: Assertion failed
mercedesme.0 | 2023-12-14 09:59:13.026 | error | Websocket parse error
mercedesme.0 | 2023-12-14 09:59:07.818 | error | Error: Failure: Invalid wire type: %s (at position %s)
mercedesme.0 | 2023-12-14 09:59:07.818 | error | Websocket parse error
mercedesme.0 | 2023-12-14 09:59:02.618 | error | Error: Assertion failed
mercedesme.0 | 2023-12-14 09:59:02.617 | error | Websocket parse error
mercedesme.0 | 2023-12-14 09:58:57.411 | error | Error: Failure: Invalid wire type: %s (at position %s)
mercedesme.0 | 2023-12-14 09:58:57.410 | error | Websocket parse error
mercedesme.0 | 2023-12-14 09:58:52.212 | error | Error: Assertion failed
mercedesme.0 | 2023-12-14 09:58:52.212 | error | Websocket parse error
mercedesme.0 | 2023-12-14 09:58:46.996 | error | Error: Failure: Invalid wire type: %s (at position %s)
mercedesme.0 | 2023-12-14 09:58:46.994 | error | Websocket parse error
...

**Comment by TA2k** [comment]
please try the GitHub version

**Comment by th10mu** [comment]
GitHub version is 0.1.3 which I tried already

**Comment by TA2k** [comment]
please try the GitHub version

**Comment by th10mu** [comment]
0.1.5 looks much better, thank you! But it still reports

State value to set for "mercedesme.0.XXXXXXX.commands.ZEV_PRECONDITION_CONFIGURE_SEATS.capabilityInformation" has to be one of type "string", "number", "boolean" but received type "object"

**Comment by th10mu** [comment]
same for

State value to set for "mercedesme.0.XXXXXXXX.commands.ZEV_PRECONDITION_CONFIGURE_SEATS.additionalInformation" has to be one of type "string", "number", "boolean" but received type "object"

**Comment by TA2k** [comment]
Please reinstall GitHub version and test again and post the content of the state

**Comment by th10mu** [comment]
Done with GitHub version 0.1.5

mercedesme.0 | 2023-12-14 11:00:01.116 | info | State  value to set for  "mercedesme.0.W1N9N0CBXRJ105618.commands.ZEV_PRECONDITION_CONFIGURE_SEATS.capabilityInformation"  has to be one of type "string", "number", "boolean" but received type  "object"
-- | -- | -- | --
mercedesme.0 | 2023-12-14 10:59:59.831 | info | State  value to set for  "mercedesme.0.W1N9N0CBXRJ105618.commands.ZEV_PRECONDITION_CONFIGURE_SEATS.additionalInformation"  has to be one of type "string", "number", "boolean" but received type  "object"
mercedesme.0 | 2023-12-14 10:59:58.145 | info | Start Websocket Connection
mercedesme.0 | 2023-12-14 10:59:58.081 | info | Creating vehicle XXXXXXXX with XXXXXXXX
mercedesme.0 | 2023-12-14 10:59:58.077 | info | Found 1 vehicles
mercedesme.0 | 2023-12-14 10:59:56.333 | info | starting.  Version 0.1.5 (non-npm: TA2k/ioBroker.mercedesme) in  /opt/iobroker/node_modules/iobroker.mercedesme, node: v18.17.1,  js-controller: 4.0.24

**Comment by TA2k** [comment]
please reinstall again

**Comment by th10mu** [comment]
No more errors or warnings :-) You are the best!

mercedesme.0 | 2023-12-14 11:09:59.562 | info | Start Websocket Connection
-- | -- | -- | --
mercedesme.0 | 2023-12-14 11:09:59.484 | info | Creating vehicle XXXXXXXX with XXXXXXXX
mercedesme.0 | 2023-12-14 11:09:59.475 | info | Found 1 vehicles
mercedesme.0 | 2023-12-14 11:09:58.029 | info | starting.  Version 0.1.5 (non-npm: TA2k/ioBroker.mercedesme) in  /opt/iobroker/node_modules/iobroker.mercedesme, node: v18.17.1,  js-controller: 4.0.24

**Comment by TA2k** [comment]
can you share the content of the state

**Comment by fuchs-1978** [comment]
> can you share the content of the state
mercedesme.0.xxxx.commands.ZEV_PRECONDITION_CONFIGURE_SEATS.capabilityInformation
["ONLY_DRIVER_OR_ALL_SEATS"]

**Comment by th10mu** [comment]
[mercedesme.0.XXXXXXXX.commands.ZEV_PRECONDITION_CONFIGURE_SEATS.json](https://github.com/TA2k/ioBroker.mercedesme/files/13672026/mercedesme.0.XXXXXXXX.commands.ZEV_PRECONDITION_CONFIGURE_SEATS.json)
