### ISSUE TITLE
Vehicle Data missing in "state" section?

### ISSUE THREAD

**Issue by PatrickDa87** [TA2k/ioBroker.mercedesme#21]
Hi, could it be possible that some vehicle states are currently missing?

I can see the "ignitionstate" in the vehicle object but the "enginestate" is not available.

Do you know the following documentation which shows the different available data fields and possible values? --> https://developer.mercedes-benz.com/sdks/android/guides/capabilities/engine

I want to run some scripts only if the engine is off. Would be very helpful if you could have a look at it. 

Thank you very much.

**Comment by TA2k** [comment]
This is the direct feed of the app nothing related to this document. Why is the ignition state not fitting?

**Comment by PatrickDa87** [comment]
Yeah, should be enough. Thank you very much.
