### ISSUE TITLE
Login not possible

### ISSUE THREAD

**Issue by Crajs20** [TA2k/ioBroker.mercedesme#212]
I have 0.1.8 and authentication is not possible since 2.4.2024.
I got the plugin authenticated until this morning, now nothing helps. I receive from Mercedes an email with the pin but this will not work and I get a new one until my account is blocked for some time and error code 500.
The other codes is 200 and login is not working.

Does anyone have an idea how to get back authenticated- maybe to reset or clear cache?
I tried also to request the code by the webpage manually and use this code in the plugin, not working....
I like this plugin and together with Evcc it's a big help.

I tried also the other versions available on iobroker, but there I dont het a mail.

Evcc has also a possibility to connect to mercedes me, which is also not working - ao its possible that Mercedes chamhed something on the backend which block the authentication.

How ots looking for other users, does the plugin connect on your site - can you authenticate?

I opened a case on Mercedes but the support was not helpful - wrong mail template....

**Comment by Crajs20** [comment]
Topic can be closed.

I added my mobile number to the Mercedes me account and used this to login at Mercedes.
Afterwards the account was fine to be used with the email on the adapter....

So looks like an problem of my Mercedes account - cool would be better information in the logs.

**Comment by TA2k** [comment]
To improve the log a log file is needed
