### ISSUE TITLE
Websocket Closed Error (Version 0.34)

### ISSUE THREAD

**Issue by PatrickDa87** [TA2k/ioBroker.mercedesme#23]
Hi,

ich erhalte nach einer gewissen Laufzeit immer den Fehler, dass der Websocket geschlossen wird und anschließend erhalte ich keine Status-Updates des Fahrzeugs mehr (siehe Bild).

Der Reconnect funktioniert nicht immer. Ist das Problem bereits bekannt?

![image](https://user-images.githubusercontent.com/74504938/99795932-eaa26a00-2b2c-11eb-8cd4-98a6a5c3d8bf.png)

**Comment by MCepheus** [comment]
Das Spielchen habe ich z.Z. auch.
![Mercedesme](https://user-images.githubusercontent.com/72047389/99812182-6a88fe00-2b46-11eb-9a46-1453fc789a28.PNG)

Mal mehrfach kurz nacheinander, mal ist für mehrere Stunden alles i.O.

**Comment by TA2k** [comment]
fixed in 0.0.37

**Comment by PatrickDa87** [comment]
Danke dir! Sieht gut aus bisher :)

**Comment by PatrickDa87** [comment]
Hi @TA2k 

ich erhalte mit der aktuellsten Version weiterhin Fehler. Jedoch scheint die App sich wieder zu verbinden. Kannst du das Bestätigen?

![me_error1](https://user-images.githubusercontent.com/74504938/99994467-5567d580-2db9-11eb-8c6a-777447ab8c86.JPG)

**Comment by MCepheus** [comment]
Bei mir läuft die 0.0.40
Seitdem habe ich im log keine Fehler mehr gehabt.

**Comment by TA2k** [comment]
Sollte mit 0.041 behoben sein

**Comment by PatrickDa87** [comment]
Danke @TA2k 
Werde ich testen. Du leistest hier echt ne mega arbeit!!! 👍
