### ISSUE TITLE
Geofencing - Gebiete-Definition und -Abfrage

### ISSUE THREAD

**Issue by Moormerlander** [TA2k/ioBroker.mercedesme#26]
Dies ist kein Bug-Report, sondern ein Feature Request:

Ich habe in der MercedesMe-App (iOS) Gebiete definiert, für die ich Push-Nachrichten bekomme wenn ich dort rein- oder rausfahre. Diese Stati wären perfekt für ein Geofencing in ioBroker, um z.B. beim Heimkommen das Garagentor zu öffnen oder andere Routinen zu starten. Könnte der Adapter diese Infos bereitstellen?

**Comment by TA2k** [comment]
Wenn du den Adapter via github installierst und neustartest sind jetzt die geofence locations drin das matching ob deine location mit dieser locations übereinstimmt müsstest du selber machen

**Comment by Moormerlander** [comment]
Das ging ja schnell - vielen Dank!
   
   Habe ich gerade alles gemacht was Du geschrieben hast und die Gefencing-Gebiete sind auch alle da. Allerdings wird der Status "isActive" nicht aktualisiert wenn ich ein Gebiet in der App aktiviere oder deaktiviere, auch nach einem Neustart des Adapters nicht. Gibt es zudem einen Trigger der das Betreten/Verlassen der Zone signalisiert?
  
  
   
  
  
   Viele Grüße,
  
  
   Holger
  
  
   
  
  
   
    TA2k <notifications@github.com> hat am 29.12.2020 13:54 geschrieben:
   
   
    
   
   
    
   
   
   Wenn du den Adapter via github installierst und neustartest sind jetzt die geofence locations drin das matching ob deine location mit dieser locations übereinstimmt müsstest du selber machen

**Comment by Moormerlander** [comment]
Kannst Du mir noch sagen  in welchem Intervall die Unterobjekte von "state" aktualisiert werden? 
Habe das lat/long matching für current position und destination position programmiert und teste nachher.

**Comment by TA2k** [comment]
Hi isActive bezieht sich glaube nur ob du es in der app aktiv hast oder nicht. Nicht ob du gerade in der Zone bist.
Die Objekte werden gepusht also ich habe kein Einfluss auf den Interval

**Comment by Moormerlander** [comment]
Habe mein Script gestern Abend mal getestet und es funktioniert! Jetzt noch die Routine fürs Garagentor einbauen und fertig. Vielen Dank für den tollen Adapter Deine prompte Unterstützung!

**Comment by TA2k** [comment]
Wenn du dein skript bereitstellst kann ich es auch in den adapter einbauen

**Comment by iobFan** [comment]
Hallo zusammen,
gibt es eine Möglichkeit einen Status einzubauen, der signalisiert, dass man das Geofence betreten/verlassen hat? Ich würde das auch gerne für eine Garagentor-Steuerung nutzen.

**Comment by TA2k** [comment]
Das wird in der App gemacht müsste man also selber implementieren
