### ISSUE TITLE
Nach update auf 0.0.43 funktioniert der Adapter nicht mehr.

### ISSUE THREAD

**Issue by PatrickDa87** [TA2k/ioBroker.mercedesme#28]
**Describe the bug**  
Nachdem ich gerade auf 0.0.43 geupdatet habe, fährt der Mercedes me Adapter nicht mehr hoch.

![image](https://user-images.githubusercontent.com/74504938/106377765-bb676f00-639f-11eb-9b1d-c898c28a9ca8.png)

**Comment by PatrickDa87** [comment]
![image](https://user-images.githubusercontent.com/74504938/106377790-d4702000-639f-11eb-9aac-8ab20cda498b.png)

**Comment by TA2k** [comment]
Kannst du den adapter in debug mode setzen und mir den log per iobroker forum schicken
https://forum.iobroker.net/user/tombox
