### ISSUE TITLE
Installation erfolgreich, Ausführung scheitert

### ISSUE THREAD

**Issue by TjadenVdF** [TA2k/ioBroker.mercedesme#3]
Hallo und danke erst mal für den Adapter. Ich würde ihn gerne nutzen, allerdings startet die Instanz nicht richtig:
![Anmerkung 2019-06-25 111312](https://user-images.githubusercontent.com/52197789/60085803-44d1ac80-973a-11e9-868c-facd20c357fa.png)

iobroker Log:
![Anmerkung 2019-06-25 110917](https://user-images.githubusercontent.com/52197789/60085653-ffad7a80-9739-11e9-8705-95ffa5df9b5b.png)

Meine Einstellungen (gibt zwei Fahrzeuge im Account):
![Anmerkung 2019-06-25 111034](https://user-images.githubusercontent.com/52197789/60085659-01773e00-973a-11e9-9f72-5d1b1318935a.png)

Objekte werden keine angelegt.

**Comment by TA2k** [comment]
Bitte auf Node 8 oder 10 updaten

**Comment by TjadenVdF** [comment]
@TA2k Dachte zwar dass ich das getan hätte - aber offenbar nicht. Danke für den Hinweis, läuft nun =)
