### ISSUE TITLE
Car Pictures

### ISSUE THREAD

**Issue by KrX3D** [TA2k/ioBroker.mercedesme#31]
Hello, is there a way to download the car pictures we can see on the app?

i mean the once from directly front and sides/back ?

**Comment by TA2k** [comment]
I cannot receive the url from the app 
They have this format
https://prodecevehicleimages.blob.core.windows.net/vehicleimages/VIN/T9/RoofClosed/Day/Doorsclosed/Centered/PerhapsFallbackImage/BE040-P27-croppedSafeSquare
