### ISSUE TITLE
unhandled promise rejection: Cannot assign to read only property

### ISSUE THREAD

**Issue by dpomt** [TA2k/ioBroker.mercedesme#32]
Hi,
habe den Adapter eben aktualisiert. Er holt sich einige Daten, gibt aber auch Fehler aus:

2021-02-17 18:29:03.366	error	(1664) TypeError: Cannot assign to read only property '4' of string '70176 Stuttgart' at objectKeys.forEach (C:\iobroker\node_modules\iobroker.mercedesme\main.js:991:34) at Array.forEach (<ano
mercedesme.0	2021-02-17 18:29:03.366	error	(1664) unhandled promise rejection: Cannot assign to read only property '4' of string '70176 Stuttgart'
mercedesme.0	2021-02-17 18:29:03.366	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
mercedesme.0	2021-02-17 18:29:03.366	error	(1664) TypeError: Cannot assign to read only property '3' of string '70176 Stuttgart' at objectKeys.forEach (C:\iobroker\node_modules\iobroker.mercedesme\main.js:991:34) at Array.forEach (<ano
mercedesme.0	2021-02-17 18:29:03.366	error	(1664) unhandled promise rejection: Cannot assign to read only property '3' of string '70176 Stuttgart'
mercedesme.0	2021-02-17 18:29:03.366	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
mercedesme.0	2021-02-17 18:29:03.366	error	(1664) TypeError: Cannot assign to read only property '2' of string '70176 Stuttgart' at objectKeys.forEach (C:\iobroker\node_modules\iobroker.mercedesme\main.js:991:34) at Array.forEach (<ano
mercedesme.0	2021-02-17 18:29:03.366	error	(1664) unhandled promise rejection: Cannot assign to read only property '2' of string '70176 Stuttgart'
mercedesme.0	2021-02-17 18:29:03.366	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
mercedesme.0	2021-02-17 18:29:03.366	error	(1664) TypeError: Cannot assign to read only property '1' of string '70176 Stuttgart' at objectKeys.forEach (C:\iobroker\node_modules\iobroker.mercedesme\main.js:991:34) at Array.forEach (<ano
mercedesme.0	2021-02-17 18:29:03.366	error	(1664) unhandled promise rejection: Cannot assign to read only property '1' of string '70176 Stuttgart'
mercedesme.0	2021-02-17 18:29:03.366	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
mercedesme.0	2021-02-17 18:29:03.366	error	(1664) TypeError: Cannot assign to read only property '0' of string '70176 Stuttgart' at objectKeys.forEach (C:\iobroker\node_modules\iobroker.mercedesme\main.js:991:34) at Array.forEach (<ano
mercedesme.0	2021-02-17 18:29:03.366	error	(1664) unhandled promise rejection: Cannot assign to read only property '0' of string '70176 Stuttgart'
mercedesme.0	2021-02-17 18:29:03.366	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
mercedesme.0	2021-02-17 18:29:03.366	error	(1664) TypeError: Cannot assign to read only property '11' of string 'Königstr. 42' at objectKeys.forEach (C:\iobroker\node_modules\iobroker.mercedesme\main.js:991:34) at Array.forEach (<anony
mercedesme.0	2021-02-17 18:29:03.366	error	(1664) unhandled promise rejection: Cannot assign to read only property '11' of string 'Königstr. 42'
mercedesme.0	2021-02-17 18:29:03.366	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
mercedesme.0	2021-02-17 18:29:03.366	error	(1664) TypeError: Cannot assign to read only property '10' of string 'Königstr. 42' at objectKeys.forEach (C:\iobroker\node_modules\iobroker.mercedesme\main.js:991:34) at Array.forEach (<anony
mercedesme.0	2021-02-17 18:29:03.350	error	(1664) unhandled promise rejection: Cannot assign to read only property '10' of string 'Königstr. 42'
mercedesme.0	2021-02-17 18:29:03.350	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

Bei den abgerufenen Daten fällt mir "addressLines" auf - woher die Adresse kommt, weiß ich nicht, sie ist mir nicht bekannt:
...
'address':{'city':'XXX','countryCode':'DE','street':'yyy','zipCode':'12345'},
'addressLines':['Königstr. 42','70176 Stuttgart','Deutschland'],
...

Irgendeine Idee was schiefläuft?
Vielen Dank!!

**Comment by tonyH23** [comment]
Ich habe das gleiche Problem und den gleichen fehler log in iobroker. Neustart bringt nix, habe den Adapter auch schon gelöscht und neu installiert. Die komische adresse habe ich auch drin.

**Comment by TA2k** [comment]
Via github installieren dann sollte es wieder gehen

**Comment by dpomt** [comment]
Vielen Dank, Fehler tritt mit der Version aus GitHub nicht mehr auf!
