### ISSUE TITLE
Auto verbinden

### ISSUE THREAD

**Issue by githubtzzz** [TA2k/ioBroker.mercedesme#39]
HAllo,

wie genau verbinde ich diesen Adapter mit Mercedes Me?
Ich bekomme zig mails mit einem 1mal COde von Mercedesme. Wenn ich einen davon eintrage und den Adapter neu starte, ändert sich nichts.
Vielen dank!

**Comment by TA2k** [comment]
Nochmal via github installieren ob das Problem dann behoben ist

**Comment by buehlisiobroker** [comment]
Es geht leider nur temporär und dann ist die Verbindung irgendwann wieder weg. Nach einen Reboot oder Neustart des Adapters wird auch wieder eine Mail (Code) gesendet.

**Comment by TA2k** [comment]
Ich bräuchte den Fehler der im Log geschrieben wird

**Comment by buehlisiobroker** [comment]
> Ich bräuchte den Fehler der im Log geschrieben wird

Wenn ich den Adapter neu starte und dann geht alles so weit, und dann ist der irgendwann einfach wieder nicht mehr verbunden. Gerade nochmals getestet. 
![Screenshot 2021-03-02 214954](https://user-images.githubusercontent.com/79419654/109713242-41462800-7ba1-11eb-9111-28f37177e057.png)
Danke!

**Comment by TA2k** [comment]
Der Moment wenn er nicht mehr verbunden ist wäre noch gut

**Comment by buehlisiobroker** [comment]
so leider hat es ca. 2 Stunden gedauert.
![Screenshot 2021-03-03 070520](https://user-images.githubusercontent.com/79419654/109760394-df141400-7bee-11eb-9a87-3b3d820b1a60.png)

**Comment by buehlisiobroker** [comment]
hier noch der Rest. Ich hoffe das hilft...
![Screenshot 2021-03-03 070812](https://user-images.githubusercontent.com/79419654/109760630-4e8a0380-7bef-11eb-830d-ca1d8d34e612.png)

**Comment by buehlisiobroker** [comment]
ich habe noch was im Log gefunden.
![Screenshot 2021-03-03 080227](https://user-images.githubusercontent.com/79419654/109766732-db848b00-7bf6-11eb-9140-368558b4ac26.png)

**Comment by TA2k** [comment]
Bitte via github installieren damit sollte es weg sein
