### ISSUE TITLE
Adapter stürzt direkt nach dem Start ab

### ISSUE THREAD

**Issue by Moormerlander** [TA2k/ioBroker.mercedesme#4]
ioBroker-Config:

Node.js: v6.11.3
NPM: 3.10.10

![2019-07-09 10_33_51-logs - ioBroker](https://user-images.githubusercontent.com/27990424/60872600-4076ba80-a235-11e9-8572-49ecd91d1edc.png)

**Comment by TA2k** [comment]
bitte node.js auf minium 8 updaten

**Comment by Moormerlander** [comment]
Vielen Dank - mit 8.16.0 läuft es einwandfrei!
