### ISSUE TITLE
Login not possible

### ISSUE THREAD

**Issue by mhoster83** [TA2k/ioBroker.mercedesme#72]
**Describe the bug**  
Since a couple of days I get the following error message. A restart and logging of didn't help.

**	(25314) Login was not successful.

	(25314) Error: Request failed with status code 400

	(25314) Not able to request login code**

**To Reproduce**  
Restart adapter

**Expected behavior**  
Successful Login

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/70483786/122240700-444ff480-cec2-11eb-8c8a-cb1981c41cf2.jpeg)

**Versions:**  
 - Adapter version: 0.0.52
 - JS-Controller version: 3.2.16
 - Node version: v10.20.1
 - Operating system: Debian9

**Comment by TA2k** [comment]
fixed with 0.0.53
