### ISSUE TITLE
Doesn't work with Smart EQ?

### ISSUE THREAD

**Issue by addmoremobile** [TA2k/ioBroker.mercedesme#8]
Hi,

i recently got a Smart EQ (which is awesome btw).
Since Smart is a part of Mercedes is supports Mercedes Me to check the current battery state and preclimatisation.
When I log into the Webinterface of mercedes me I can see and control my car.

But if I start the adapter in ioBroker the log says:

`mercedesme.0 | 2019-12-17 12:43:42.454 | warn | (15199) No vehicles found`

Do you have any suggestions on that?

Thanks for the great work,
Moritz

**Comment by TA2k** [comment]
Did you test it with the mercedes me app?
Pleae contact me in the iobroker forum via pn
https://forum.iobroker.net/user/tombox 3 dots in the right.
