### ISSUE TITLE
SOC beim EQV immer wieder Sprünge auf 0%

### ISSUE THREAD

**Issue by fuchs-1978** [TA2k/ioBroker.mercedesme#95]
Ich lese den SOC meines EQV aus.

mercedesme.0.W1V4xxxxxxxxxxxxx3.state.soc.displayValue. In unregelmäßigen Abständen springt der Wert immer wieder kurz auf 0%. 

Also das Auto hat 68%, für eine Sekunde springt der Wert auf 0% und dann wieder zurück auf 68%.

**Comment by fuchs-1978** [comment]
Ja bei intValue gleiches verhalten. Debug muss ich Mal probieren

**Comment by PatrickDa87** [comment]
@fuchs-1978: Ich nutze ebenfalls den SOC DisplayValue und ich konnte das Problem bisher nicht feststellen. Ich werde den Datenpunkt mal im History Adapter tracken und schauen, ob es evtl. bei mir auch auftritt.

**Comment by fuchs-1978** [comment]
Ich habe inzwischen einen workaround ich bearbeite die Werte mit Javascript und lösche die Werte mit null. Ist ja als soc unrealistisch
